title: 내가 보려고 모아 놓은 TIPs
email: uhooaha@kakao.com
greeting: 내가 보려고 모아 놓은 TIPs
# remote_theme: ezrasavard/israh
description: > # this means to ignore newlines until another tag
    Israh is a responsive Jekyll theme with warm greys, a single column layout, and not much else.
favicon: favicon.png
navLinks:
    -
        text: Home
        url: /
        internal: True
    -
        text: The Theme
        url: /theme
        internal: True
    -
        text: Github
        url: https://www.github.com/ezrasavard
        internal: False
    -
        text: LinkedIn
        url: https://www.linkedin.com/in/ezrasavard
        internal: False
category_list: [AI 활용팁, 깃허브 페이지 만들기, 디자인 작업팁, 생활에 필요한 팁]

# Build settings
paginate: 3
baseurl: "" # the subpath of your site, e.g. /blog/
#baseurl: ""
url: "https://chungchoon98.com" # the base hostname & protocol for your site
highlights: pygments
# permalink: posts/:title/
include: ["_pages"]
plugins: [jekyll-paginate]
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
    sass_dir: _sass
    style: compressed
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "uhooaha"
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            author: "uhooaha"
            layout: "page"

collections:
  posts:
    output: true
permalink: /:title/
